### ISSUE TITLE
tidb todo

### ISSUE THREAD

**Issue by mccxj** [mccxj/mccxj.github.io#13]
- "div" scientific notation values out of range #4477

**Comment by mccxj** [comment]
- check invalid charset when create database. #4486

**Comment by mccxj** [comment]
- [ ] incorrect result of cast double to datetime #4462

**Comment by mccxj** [comment]
- [ ] ROUND() behavior on floating-point types compatibility #4404

**Comment by mccxj** [comment]
- [ ] type inference of `@@GLOBAL.sql_mode` and `@@SESSION.sql_mode` is incorrect #4251

**Comment by mccxj** [comment]
// MarshalJSON implements json.Marshaler interface.
func (sf *ScalarFunction) MarshalJSON() ([]byte, error) {
    buffer := bytes.NewBufferString(fmt.Sprintf("\"%s\"", sf))
    return buffer.Bytes(), nil
}

**Comment by mccxj** [comment]
// String implements fmt.Stringer interface.
func (sf *ScalarFunction) String() string {
    result := sf.FuncName.L + "("
    for i, arg := range sf.GetArgs() {
        result += arg.String()
        if i+1 != len(sf.GetArgs()) {
            result += ", "
        }
    }
    result += ")"
    return result
}
